### PR TITLE
Add script to generate event template file, add also template file.

### PR DESCRIPTION
**Pull request by jknodlseder**
I created a Python script that generates an event template file. The file is actually more complete than the description on the web page. Please inspect the files and send me any comments. You may also use the script and play around with generating event files (needs the gammalib Python module).

### CODE REVIEW

**Comment by cdeil** [comment]
Thank you!

From my side, this looks OK and can go in as soon as #39 is in without further review (apart from you checking consistency once).

I plan to update the event list code and [event list checker in Gammapy](https://gammapy.readthedocs.org/en/latest/api/gammapy.data.EventListDatasetChecker.html) and then also check this file, but I won't get to it before I go on vacation, so this will be in 1 month, and this should go in now.

**Comment by cdeil** [comment]
@jknodlseder - Assigning for you to review.

**Comment by jknodlseder** [comment]
??? I should review my own pull request ???

**Comment by jknodlseder** [comment]
By the way: would like to update #39 to make it consistent with #40

**Comment by cdeil** [comment]
OK, I'll review that one as well, put me as assignee again.
Should I look at this one now, or do you first want to adress my comments on #39 and then I have one last look at both?

**Comment by cdeil** [comment]
@jknodlseder - Now that #39 is merged: is this PR ready for review or do you know that it's inconsistent / you want to update it?

The current version of the spec is here:
http://gamma-astro-data-formats.readthedocs.io/en/latest/events/index.html

For the POINTING table, I see that you have some code to fill values. Are those supposed to be correct values that people can use to test their codes?
If no, using [gammapy.data.PointingInfo](https://gammapy.readthedocs.io/en/latest/api/gammapy.data.PointingInfo.html) here might be an option that can (at least should) be able to generate correct ALT / AZ.

**Comment by cdeil** [comment]
@jknodlseder - Do you have time to finish this up next week?

(I'm setting the v0.2 milestone to June 17, end of next week.)

Alternatively, I could start a new pull request with a similar script, using astropy.io.fits, to create example files for the spec.

**Comment by cdeil** [comment]
@jknodlseder - Do you have time to finish up this PR?

It doesn't have to be perfect. If we have it in master, everyone can continue and make updates to the format / scripts.

**Comment by cdeil** [comment]
In HESS we now have approval to go ahead with the public FITS test data release, and we'd like to do the release in June, and before I'd like to make a stable version of the spec.

@jknodlseder - Do you have interest / time to finish this PR with the example for EVENTS, GTI, POINTING with Gammalib?

If yes, I would do a detailed review in the next days.
If no, I would take over (and change the examples script to Astropy/Gammapy at least for the parts filling coordinates, because I know those well).

One issue I noticed is that you currently fill ALT_PNT > 90 in the POINTING table, which isn't valid, and then Gammapy can't process it properly:
```
>>> from astropy.table import Table
>>> Table.read('source/events/events.fits', hdu=3)[:2]
<Table length=2>
  TIME   RA_PNT DEC_PNT ALT_PNT  AZ_PNT
   s      deg     deg     deg     deg  
float64 float32 float32 float32 float32
------- ------- ------- ------- -------
    0.0 83.6331 22.0145 111.441 40.7226
   60.0 83.6331 22.0145 111.727 40.8477
>>> from gammapy.data import PointingInfo
>>> p = PointingInfo.read('source/events/events.fits', hdu=3)
>>> print(p)
Traceback (most recent call last):
  File "/Users/deil/Library/Python/3.5/lib/python/site-packages/astropy/utils/decorators.py", line 734, in __get__
    return obj.__dict__[self._key]
KeyError: 'altaz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/deil/code/gammapy/gammapy/data/pointing.py", line 78, in __str__
    ss += '\nSTART:\n' + self._str_for_index(0) + '\n'
  File "/Users/deil/code/gammapy/gammapy/data/pointing.py", line 88, in _str_for_index
    ss += 'ALTAZ: {} deg\n'.format(self.altaz[idx].to_string())
  File "/Users/deil/Library/Python/3.5/lib/python/site-packages/astropy/utils/decorators.py", line 736, in __get__
    val = self.fget(obj)
  File "/Users/deil/code/gammapy/gammapy/data/pointing.py", line 135, in altaz
    return SkyCoord(lon, lat, unit='deg', frame=self.altaz_frame)
  File "/Users/deil/Library/Python/3.5/lib/python/site-packages/astropy/coordinates/sky_coordinate.py", line 212, in __init__
    kwargs = self._parse_inputs(args, kwargs)
  File "/Users/deil/Library/Python/3.5/lib/python/site-packages/astropy/coordinates/sky_coordinate.py", line 345, in _parse_inputs
    coord_kwargs[frame_attr_name] = attr_class(arg, unit=unit)
  File "/Users/deil/Library/Python/3.5/lib/python/site-packages/astropy/coordinates/angles.py", line 498, in __new__
    self._validate_angles()
  File "/Users/deil/Library/Python/3.5/lib/python/site-packages/astropy/coordinates/angles.py", line 515, in _validate_angles
    'got {0}'.format(angles.to(u.degree)))
ValueError: Latitude angle(s) must be within -90 deg <= angle <= 90 deg, got [ 111.44076538  111.72663879  112.01358795  112.30161285  112.59072876
  112.88092041  113.17221069  113.46458435  113.75805664  114.05261993
  114.34827423  114.64502716  114.94288635  115.24184418  115.54190063
  115.84305573  116.14531708  116.44868469  116.75315857  117.05873108
  117.36541748  117.67320251  117.98209381  118.29209137  118.60319519
  118.91540527  119.22871399  119.54312897  119.85864258  120.17525482
  120.4929657 ] deg
```

**Comment by cdeil** [comment]
The other thing I noticed is that Gammapy can't process the EVENTS given here because e.g. `RA_PNT` is missing from the EVENTS header.

I only now see that in #39 you removed pointing parameters like `RA_PNT` from the EVENTS header in the spec!???

What is the status of using the POINTING table in Gammalib? Is it fully implemented and tested? If the arrays moves around during an observation, do you handle this correctly for a binned analysis?

My strong preference would be that we now, for a first stable version of the spec, go back to the well-tested and widely used (e.g. by HESS, VERITAS, MAGIC, ?CTA?) format where the pointing info is in the EVENTS header and only fixed-pointing is supported. (and mention the pointing table as the likely future way to do it, to be prototyped and fleshed out by science tools).

**Comment by cdeil** [comment]
In the latest version of the events files I have from you from 1DC there's no POINTING table:
```
$ ftlist data/1dc_test/data//gps_baseline_000001.fits
Print options: H C K I T [H] 

        Name               Type       Dimensions
        ----               ----       ----------
HDU 1   Primary Array      Null Array                               
HDU 2   EVENTS             BinTable     7 cols x 135398 rows        
HDU 3   GTI                BinTable     2 cols x 1 rows             
```
@jknodlseder - OK to go back to having the fixed pointing parameters in the EVENTS header in the for now, to avoid that all current files we have from IACTs are invalid wrt the spec?

**Comment by cdeil** [comment]
I'm closing this old PR now: no reply / update since 2016.

Note that all IACTs are about to release some example FITS files in this format, and CTA did so with the first data challenge.

We still want to have such a script and example file where we control the content and can update as the spec evolves. So if anyone is willing to write this and make a new PR (could be based on this one if you like), please go ahead any time!

**Pull request closed without merging**
